sudo: required

services:
- docker

before_install:
- docker pull debian:7

script:
- |
  if [ -z "${TRAVIS_TAG}" ]; then
    mkdir output
    docker run --rm=true -e "USERID=${UID}" -v `pwd`:/src:rw debian:7 /bin/sh -c "cd src && ./docker-setup.sh";
    find output
  fi

before_deploy:
- mkdir output
- docker run --rm=true -e "USERID=${UID}" -v `pwd`:/src:rw debian:7 /bin/sh -c "cd src && ./docker-setup.sh"
- cd output
- tar cjf libs.tar.bz2 *
- tar tf libs.tar.bz2

deploy:
  provider: releases
  api_key:
    secure: aSyegzSgvfQz9tsxH4BvpOW8b86QRfT3ESk/9di6Pgo656hxUtnKY0cE8Zc3k5uh3eD92XqFXzK1euoS16g66uQnrg7LSSq1EKLBR4ejqa29vRMEfwoESN5uQRJKrxYf0Z1FSrImewwAumrOh/t8nLUjR95CDOgpBWpQQeCr3yraOUf+ifb0nax8Wch87qFQRjBsTSjKR54LTfMam+VUcQoyjuz7CPJHNabChxLTbu36n54J5f4KwjIGlLTsGKLbnnWMfuHPPmalDcL0JXcgcldOIlLBL6aHJnwqR0wAuVJML5xuncxIUbTPGeBaeYWGufwt2ZC5yy+JxcdCdlYxBS5Qj7Iff8aPJ5IlY5KHHWUtdQNebQvnJjWGrH2kKZmmdum4yeTOXWObSYKX3uNTyDeYteHquUGU/4R2PpCo90Wkrqxr6/J0k3WjXrchVARfWDfa9neAHCFxejAJs+IbkIcH90kyMKZQISFjpSledhlVHWPVAt9izKdf0dRNvVj2HrWlZht5JhoQ7pbN8ikds6QQYm5BMxG4OoFYPe1coLEgRFnV6BqUQrD+RbyPm6B85VnMDkn8BMOHA6V1GTyqDGs3mGpCmkANmVJspMYcEFNMrYAWLbIguT1URCApgczB/LTwVBIs3mElcsVzisaWyOyxY8TmIzyKvM4vf8rYvZE=
  file: libs.tar.bz2
  skip_cleanup: true
  on:
    tags: true
