dist: trusty

addons:
  apt:
    packages:
      - libopenal1
      - libncurses-dev
      - libreadline-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libx11-dev
      - libxcursor-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
      - libxt-dev

script:
- |
  if [ -z "${TRAVIS_TAG}" ]; then
    ./build.sh
  fi

before_deploy:
- ./build.sh

deploy:
  provider: releases
  api_key:
    secure: aSyegzSgvfQz9tsxH4BvpOW8b86QRfT3ESk/9di6Pgo656hxUtnKY0cE8Zc3k5uh3eD92XqFXzK1euoS16g66uQnrg7LSSq1EKLBR4ejqa29vRMEfwoESN5uQRJKrxYf0Z1FSrImewwAumrOh/t8nLUjR95CDOgpBWpQQeCr3yraOUf+ifb0nax8Wch87qFQRjBsTSjKR54LTfMam+VUcQoyjuz7CPJHNabChxLTbu36n54J5f4KwjIGlLTsGKLbnnWMfuHPPmalDcL0JXcgcldOIlLBL6aHJnwqR0wAuVJML5xuncxIUbTPGeBaeYWGufwt2ZC5yy+JxcdCdlYxBS5Qj7Iff8aPJ5IlY5KHHWUtdQNebQvnJjWGrH2kKZmmdum4yeTOXWObSYKX3uNTyDeYteHquUGU/4R2PpCo90Wkrqxr6/J0k3WjXrchVARfWDfa9neAHCFxejAJs+IbkIcH90kyMKZQISFjpSledhlVHWPVAt9izKdf0dRNvVj2HrWlZht5JhoQ7pbN8ikds6QQYm5BMxG4OoFYPe1coLEgRFnV6BqUQrD+RbyPm6B85VnMDkn8BMOHA6V1GTyqDGs3mGpCmkANmVJspMYcEFNMrYAWLbIguT1URCApgczB/LTwVBIs3mElcsVzisaWyOyxY8TmIzyKvM4vf8rYvZE=
  file: libs.tar.bz2
  skip_cleanup: true
  on:
    tags: true
